import clsx from "clsx";
import { useKeenSlider } from "keen-slider/react";
import Head from "next/head";
import Image from "next/image";
import { BiEdit } from "react-icons/bi";
import {
	BsCodeSlash,
	BsFacebook,
	BsFillArrowLeftCircleFill,
	BsFillArrowRightCircleFill,
	BsInstagram,
	BsMegaphone
} from "react-icons/bs";
import { MdOutlinePersonPin, MdOutlineRocketLaunch } from "react-icons/md";
import { TfiBarChart } from "react-icons/tfi";
import { SectionReveal } from "~/components/reveal";
import { productSans } from "~/shared";
import { feedbacks } from "~/utils/feedbacks";

const ClientSlide: React.FC<{
	name: string;
	vacation: string;
	description: string;
	avatar: string;
}> = ({ avatar, name, vacation, description }) => {
	return (
		<div
			className={clsx(
				"h-56",
				"bg-[#F8F9FF]",
				"hover:bg-[#FF5100]",
				"hover:cursor-pointer",
				"rounded-lg",
				"p-4",
				"flex",
				"flex-col",
				"gap-4",
				"group"
			)}
		>
			<div className={clsx("flex", "flex-row", "items-center", "gap-4")}>
				<div
					className={clsx("w-16", "h-16", "rounded-full", "bg-slate-200")}
				/>
				<div>
					<strong
						className={clsx(
							productSans.className,
							"group-hover:text-white",
							"text-lg"
						)}
					>
						{name}
					</strong>
					<p
						className={clsx(
							productSans.className,
							"group-hover:text-white",
							"text-sm"
						)}
					>
						{vacation}
					</p>
				</div>
			</div>
			<p
				className={clsx(
					productSans.className,
					"text-sm",
					"line-clamp-5",
					"group-hover:text-white"
				)}
			>
				{description}
			</p>
		</div>
	);
};

export default function Home() {
	const [ref] = useKeenSlider<HTMLUListElement>({
		slides: { perView: 3, spacing: 16 }
	});

	return (
		<>
			<Head>
				<title>Aggencia</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/svgs/logo.svg" />
				<link
					rel="preload"
					as="image"
					type="image/svg+xml"
					href="/svgs/wave.svg"
				/>
			</Head>
			<header>
				<nav className={clsx("p-4", "bg-white")}>
					<div
						className={clsx(
							"container",
							"flex",
							"flex-row",
							"justify-between",
							"gap-8",
							"m-auto"
						)}
					>
						<div
							className={clsx(
								"flex",
								"flex-row",
								"items-center",
								"gap-4"
							)}
						>
							<div className={clsx("relative", "w-9", "h-9")}>
								<Image
									priority
									fill
									src="/svgs/logo.svg"
									alt="aggencia-logo"
								/>
							</div>
							<h2
								className={clsx(
									productSans.className,
									"font-bold",
									"text-xl"
								)}
							>
								Aggencia
							</h2>
						</div>
						<div
							className={clsx(
								"flex",
								"flex-row",
								"items-center",
								"gap-8"
							)}
						>
							<a href="#metodos">
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-xl",
										"hover:cursor-pointer",
										"hover:text-[#FF5100]"
									)}
								>
									Método
								</p>
							</a>
							<a href="#especialidades">
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-xl",
										"hover:cursor-pointer",
										"hover:text-[#FF5100]"
									)}
								>
									Especialidades
								</p>
							</a>
							<a href="#testemunhos">
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-xl",
										"hover:cursor-pointer",
										"hover:text-[#FF5100]"
									)}
								>
									Testemunhos
								</p>
							</a>
							<a href="#sobre-nos">
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-xl",
										"hover:cursor-pointer",
										"hover:text-[#FF5100]"
									)}
								>
									Sobre Nós
								</p>
							</a>
						</div>
					</div>
				</nav>
			</header>
			<main>
				<section>
					<div
						className={clsx(
							"container",
							"flex",
							"flex-row",
							"justify-between",
							"items-center",
							"h-[24rem]",
							"relative",
							"m-auto"
						)}
					>
						<div
							className={clsx(
								"absolute",
								"top-0",
								"h-[36rem]",
								"flex",
								"flex-row",
								"items-center",
								"gap-4"
							)}
						>
							<div className={clsx("flex", "flex-col", "gap-6")}>
								<h1
									className={clsx(
										productSans.className,
										"text-5xl",
										"font-bold",
										"text-black"
									)}
								>
									Venda no Google <br />
									<span className="text-[#FF5100]">
										todos os dias.
									</span>
								</h1>
								<h2>
									Tenha uma estratégia de marketing específica para o
									seu negócio criado por especialistas em Google Ads.
								</h2>
								<button
									className={clsx(
										productSans.className,
										"font-bold",
										"text-white",
										"bg-[#FF5100]",
										"rounded-xl",
										"text-lg",
										"h-16",
										"w-64",
										"shadow-[4px_4px_48px_4px_rgba(0,0,0,0.1)]",
										"hover:cursor-pointer",
										"hover:opacity-40"
									)}
								>
									Entre em Contato
								</button>
							</div>
							<aside
								className={clsx(
									"min-w-[36rem]",
									"h-[36rem]",
									"z-10",
									"relative"
								)}
							>
								<Image
									fill
									priority
									src="/svgs/meme-content.svg"
									alt="meme-content"
									placeholder="blur"
									blurDataURL={"/meme-content.svg"}
									className={clsx("animate-fly")}
								/>
							</aside>
						</div>
					</div>
				</section>
				<div className={clsx("w-full", "h-[450px]", "relative")}>
					<Image
						fill
						priority
						alt="wave"
						src="/svgs/wave.svg"
						placeholder="blur"
						blurDataURL={"/wave.svg"}
					/>
				</div>
				<SectionReveal id="metodos">
					<div className={clsx("container", "relative", "m-auto")}>
						<h2
							className={clsx(
								productSans.className,
								"relative",
								"text-black",
								"font-bold",
								"text-4xl",
								"text-center",
								"pb-4",
								"after:absolute",
								"after:content-['']",
								"after:rounded-xl",
								"after:border-b-4",
								"after:border-[#FF5100]",
								"after:bottom-0",
								"after:left-[50%]",
								"after:-ml-[50px]",
								"after:w-24",
								"after:m-auto"
							)}
						>
							Conheça nosso método
						</h2>
						<div className={clsx("flex", "flex-col", "mt-16", "gap-8")}>
							<div
								className={clsx(
									"h-48",
									"w-2/3",
									"bg-white",
									"relative",
									"place-self-start",
									"rounded-lg",
									"shadow-[4px_4px_48px_4px_rgba(0,0,0,0.1)]",
									"items-center",
									"flex",
									"flex-row",
									"px-4",
									"gap-4",
									"animate-fly"
								)}
							>
								<div
									className={clsx("relative", "h-36", "min-w-[9rem]")}
								>
									<Image
										fill
										src="/svgs/testimonial.svg"
										alt="testimonial"
									/>
								</div>
								<div className={clsx("flex", "flex-col", "gap-2")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-3xl",
											"relative",
											"pb-2",
											"after:absolute",
											"after:content-['']",
											"after:rounded-xl",
											"after:border-b-4",
											"after:border-[#FF5100]",
											"after:bottom-0",
											"after:left-0",
											"after:w-16"
										)}
									>
										Objetivo
									</p>
									<p className={clsx(productSans.className)}>
										Para ajudar a sua empresa a crescer, primeiro
										buscamos entender o produto que ela vende, os
										objetivos e as limitações. Com isso em mente,
										partimos para a parte 2.
									</p>
								</div>
								<div className={clsx("absolute", "-top-8", "-left-8")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-7xl",
											"text-[#FF5100]",
											"opacity-50"
										)}
									>
										01
									</p>
								</div>
							</div>
							<div
								className={clsx(
									"h-48",
									"w-2/3",
									"bg-white",
									"relative",
									"place-self-end",
									"rounded-lg",
									"shadow-[4px_4px_48px_4px_rgba(0,0,0,0.1)]",
									"items-center",
									"flex",
									"flex-row",
									"px-4",
									"gap-4",
									"animate-fly"
								)}
							>
								<div className={clsx("flex", "flex-col", "gap-2")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-3xl",
											"relative",
											"pb-2",
											"after:absolute",
											"after:content-['']",
											"after:rounded-xl",
											"after:border-b-4",
											"after:border-[#FF5100]",
											"after:bottom-0",
											"after:left-0",
											"after:w-16"
										)}
									>
										Concorrentes
									</p>
									<p className={clsx(productSans.className)}>
										Todo mundo quer ser maior que os concorrentes.
										Para alcançar isso, os estudamos para ver o que
										eles fazem que dá certo e o que da errado. Assim,
										economizamos seu dinheiro, tempo e esforço para
										alcançar anúncios vencedores.
									</p>
								</div>
								<div
									className={clsx("relative", "h-36", "min-w-[9rem]")}
								>
									<Image
										fill
										src="/svgs/concorrentes.svg"
										alt="concorrentes"
									/>
								</div>
								<div className={clsx("absolute", "-top-8", "-right-8")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-7xl",
											"text-[#FF5100]",
											"opacity-50"
										)}
									>
										02
									</p>
								</div>
							</div>
							<div
								className={clsx(
									"h-48",
									"w-2/3",
									"bg-white",
									"relative",
									"place-self-start",
									"rounded-lg",
									"shadow-[4px_4px_48px_4px_rgba(0,0,0,0.1)]",
									"items-center",
									"flex",
									"flex-row",
									"px-4",
									"gap-4",
									"animate-fly"
								)}
							>
								<div
									className={clsx("relative", "h-36", "min-w-[9rem]")}
								>
									<Image
										fill
										src="/svgs/estrategia.svg"
										alt="estratégia"
									/>
								</div>
								<div className={clsx("flex", "flex-col", "gap-2")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-3xl",
											"relative",
											"pb-2",
											"after:absolute",
											"after:content-['']",
											"after:rounded-xl",
											"after:border-b-4",
											"after:border-[#FF5100]",
											"after:bottom-0",
											"after:left-0",
											"after:w-16"
										)}
									>
										Estratégia
									</p>
									<p className={clsx(productSans.className)}>
										Entendendo como seus concorrentes trabalham,
										partimos para a montagem de uma estratégia
										especifica para o seu negócio, buscando sempre
										gastar o menos possível por cada venda.
									</p>
								</div>
								<div className={clsx("absolute", "-top-8", "-left-8")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-7xl",
											"text-[#FF5100]",
											"opacity-50"
										)}
									>
										03
									</p>
								</div>
							</div>
							<div
								className={clsx(
									"h-48",
									"w-2/3",
									"bg-white",
									"relative",
									"place-self-end",
									"rounded-lg",
									"shadow-[4px_4px_48px_4px_rgba(0,0,0,0.1)]",
									"items-center",
									"flex",
									"flex-row",
									"px-4",
									"gap-4",
									"animate-fly"
								)}
							>
								<div className={clsx("flex", "flex-col", "gap-2")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-3xl",
											"relative",
											"pb-2",
											"after:absolute",
											"after:content-['']",
											"after:rounded-xl",
											"after:border-b-4",
											"after:border-[#FF5100]",
											"after:bottom-0",
											"after:left-0",
											"after:w-16"
										)}
									>
										Lançamento
									</p>
									<p className={clsx(productSans.className)}>
										Após todos os passos anteriores, partimos para a
										ação. Lançamos os seus anúncios seguindo o
										planejamento a risca para obtermos o melhor
										resultado possível para a sua empresa.
									</p>
								</div>
								<div
									className={clsx("relative", "h-36", "min-w-[9rem]")}
								>
									<Image
										fill
										src="/svgs/lancamento.svg"
										alt="lançamento"
									/>
								</div>
								<div className={clsx("absolute", "-top-8", "-right-8")}>
									<p
										className={clsx(
											productSans.className,
											"font-bold",
											"text-7xl",
											"text-[#FF5100]",
											"opacity-50"
										)}
									>
										04
									</p>
								</div>
							</div>
						</div>
					</div>
				</SectionReveal>
				<SectionReveal id="especialidades">
					<div
						className={clsx("container", "relative", "mt-36", "m-auto")}
					>
						<div className={clsx("especialidades-grid", "h-[24rem]")}>
							<div
								className={clsx(
									"[grid-area:a]",
									"bg-[#F8F9FF]",
									"rounded-xl",
									"flex",
									"flex-col",
									"items-center",
									"justify-center",
									"gap-4",
									"p-8"
								)}
							>
								<BsMegaphone
									size={36}
									color="#FF5100"
									className={clsx("rotate-[-24deg]")}
								/>
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-center",
										"text-black"
									)}
								>
									Campanhas para Google Ads
								</p>
							</div>
							<div
								className={clsx(
									"[grid-area:b]",
									"bg-[#F8F9FF]",
									"rounded-xl",
									"flex",
									"flex-col",
									"items-center",
									"justify-center",
									"gap-4",
									"p-8"
								)}
							>
								<BsCodeSlash size={36} color="#FF5100" />
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-center",
										"text-black"
									)}
								>
									Desenvolvimento e Design de Sites
								</p>
							</div>
							<div
								className={clsx(
									"[grid-area:c]",
									//"bg-[#F8F9FF]",
									"rounded-xl",
									"flex",
									"flex-col",
									"items-center",
									"justify-center",
									"p-8"
								)}
							>
								<h2
									className={clsx(
										productSans.className,
										"relative",
										"text-black",
										"font-bold",
										"text-4xl",
										"text-center",
										"pb-4",
										"after:absolute",
										"after:content-['']",
										"after:rounded-xl",
										"after:border-b-4",
										"after:border-[#FF5100]",
										"after:bottom-0",
										"after:left-[50%]",
										"after:-ml-[50px]",
										"after:w-24",
										"after:m-auto"
									)}
								>
									Nossas Especialidades
								</h2>
								<p
									className={clsx(
										productSans.className,
										"text-slate-600",
										"text-center",
										"text-lg",
										"mt-2"
									)}
								>
									Profissionais especializados e prontos para te
									entregar resultado e te ajudar a vender todos os dias
									através do Google Ads.
								</p>
							</div>
							<div
								className={clsx(
									"[grid-area:e]",
									"bg-[#F8F9FF]",
									"rounded-xl",
									"flex",
									"flex-col",
									"items-center",
									"justify-center",
									"gap-4",
									"p-8"
								)}
							>
								<BiEdit size={36} color="#FF5100" />
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-center",
										"text-black"
									)}
								>
									Elaboração de Copys
								</p>
							</div>
							<div
								className={clsx(
									"[grid-area:f]",
									"bg-[#F8F9FF]",
									"rounded-xl",
									"flex",
									"flex-col",
									"items-center",
									"justify-center",
									"gap-4",
									"p-8"
								)}
							>
								<TfiBarChart size={36} color="#FF5100" />
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-center",
										"text-black"
									)}
								>
									Otimização de Campanhas
								</p>
							</div>
							<div
								className={clsx(
									"[grid-area:g]",
									"bg-[#F8F9FF]",
									"rounded-xl",
									"flex",
									"flex-col",
									"items-center",
									"justify-center",
									"gap-4",
									"p-8"
								)}
							>
								<MdOutlinePersonPin size={36} color="#FF5100" />
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-center",
										"text-black"
									)}
								>
									Estudo de Persona e Concorrentes
								</p>
							</div>
							<div
								className={clsx(
									"[grid-area:h]",
									"bg-[#F8F9FF]",
									"rounded-xl",
									"flex",
									"flex-col",
									"items-center",
									"justify-center",
									"gap-4",
									"p-8"
								)}
							>
								<MdOutlineRocketLaunch size={36} color="#FF5100" />
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-center",
										"text-black"
									)}
								>
									Alavancagem de Vendas
								</p>
							</div>
						</div>
					</div>
				</SectionReveal>
				<SectionReveal id="testemunhos">
					<div
						className={clsx(
							"container",
							"relative",
							"m-auto",
							"mt-36",
							"flex",
							"flex-col",
							"gap-8"
						)}
					>
						<div
							className={clsx(
								"flex",
								"flex-row",
								"justify-between",
								"items-center",
								"gap-8"
							)}
						>
							<div className={clsx("flex", "flex-col", "w-[36rem]")}>
								<h2
									className={clsx(
										productSans.className,
										"relative",
										"text-black",
										"font-bold",
										"text-4xl",
										"pb-4",
										"after:absolute",
										"after:content-['']",
										"after:rounded-xl",
										"after:border-b-4",
										"after:border-[#FF5100]",
										"after:bottom-0",
										"after:left-[32%]",
										"after:w-24",
										"after:m-auto"
									)}
								>
									O que nossos clientes dizem
								</h2>
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"mt-2"
									)}
								>
									De lojistas a prestadores de serviço, atendemos e
									ajudamos qualquer tipo de negócio local a triplicar
									suas vendas na internet.
								</p>
							</div>
							<div
								className={clsx(
									"flex",
									"flex-row",
									"items-center",
									"gap-4"
								)}
							>
								<BsFillArrowLeftCircleFill
									size={48}
									className={clsx(
										"text-[#ccc]",
										"hover:text-[#FF5100]",
										"hover:cursor-pointer"
									)}
								/>
								<BsFillArrowRightCircleFill
									size={48}
									className={clsx(
										"text-[#ccc]",
										"hover:text-[#FF5100]",
										"hover:cursor-pointer"
									)}
								/>
							</div>
						</div>
						<ul ref={ref} className={clsx("keen-slider", "h-full")}>
							{feedbacks.map((data, index) => {
								return (
									<li
										key={index}
										className={clsx(
											`keen-slider__slide`,
											`number-slide${index}`,
											"group"
										)}
									>
										<ClientSlide
											name={data.name}
											vacation={data.vacation}
											avatar={data.avatar}
											description={data.description}
										/>
									</li>
								);
							})}
						</ul>
					</div>
				</SectionReveal>
				<SectionReveal>
					<div
						className={clsx(
							"container",
							"relative",
							"m-auto",
							"flex",
							"flex-row",
							"items-center",
							"justify-between",
							"mt-24"
						)}
					>
						<div className={clsx("conquests-grid")}>
							<div className={clsx("[grid-area:header]")}>
								<h2
									className={clsx(
										productSans.className,
										"relative",
										"text-black",
										"font-bold",
										"text-4xl",
										"text-left",
										"pb-4",
										"after:absolute",
										"after:content-['']",
										"after:rounded-xl",
										"after:border-b-4",
										"after:border-[#FF5100]",
										"after:bottom-0",
										"after:left-[24%]",
										"after:w-16",
										"after:m-auto"
									)}
								>
									Nossas Conquistas
								</h2>
							</div>
							<div
								className={clsx(
									"flex",
									"flex-col",
									"gap-1",
									"[grid-area:a]"
								)}
							>
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-3xl",
										"text-[#FF5100]"
									)}
								>
									R$ 100K+
								</p>
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-black"
									)}
								>
									Gerenciados em anúncios
								</p>
							</div>
							<div
								className={clsx(
									"flex",
									"flex-col",
									"gap-1",
									"[grid-area:b]"
								)}
							>
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-3xl",
										"text-[#FF5100]"
									)}
								>
									4.000+
								</p>
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-black"
									)}
								>
									Leads Gerados
								</p>
							</div>
							<div
								className={clsx(
									"flex",
									"flex-col",
									"gap-1",
									"[grid-area:c]"
								)}
							>
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-3xl",
										"text-[#FF5100]"
									)}
								>
									24+
								</p>
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-black"
									)}
								>
									Sites que VENDEM criados
								</p>
							</div>
							<div
								className={clsx(
									"flex",
									"flex-col",
									"gap-1",
									"[grid-area:d]"
								)}
							>
								<p
									className={clsx(
										productSans.className,
										"font-bold",
										"text-3xl",
										"text-[#FF5100]"
									)}
								>
									16+
								</p>
								<p
									className={clsx(
										productSans.className,
										"text-lg",
										"text-black"
									)}
								>
									Nichos Atendidos
								</p>
							</div>
						</div>
						<aside
							className={clsx("min-w-[36rem]", "h-[36rem]", "relative")}
						>
							<Image
								fill
								priority
								src="/svgs/ship.svg"
								alt="ship-content"
								placeholder="blur"
								blurDataURL={"/ship.svg"}
							/>
						</aside>
					</div>
				</SectionReveal>
				<SectionReveal id="sobre-nos">
					<div
						className={clsx(
							"container",
							"relative",
							"m-auto",
							"flex",
							"flex-row",
							"items-center",
							"justify-between",
							"mt-24",
							"gap-8"
						)}
					>
						<aside
							className={clsx("min-w-[36rem]", "h-[36rem]", "relative")}
						>
							<Image
								fill
								priority
								src="/svgs/why.svg"
								alt="why-content"
								placeholder="blur"
								blurDataURL={"/why.svg"}
							/>
						</aside>
						<div className={clsx("flex", "flex-col", "w-[36rem]")}>
							<h2
								className={clsx(
									productSans.className,
									"relative",
									"text-black",
									"font-bold",
									"text-4xl",
									"text-left",
									"pb-4",
									"after:absolute",
									"after:content-['']",
									"after:rounded-xl",
									"after:border-b-4",
									"after:border-[#FF5100]",
									"after:bottom-0",
									"after:left-[32%]",
									"after:w-24",
									"after:m-auto"
								)}
							>
								Por que a Aggencia?
							</h2>
							<p
								className={clsx(
									productSans.className,
									"text-lg",
									"mt-2",
									"text-black"
								)}
							>
								<span className={clsx("inline-block")}>
									Saber apertar os botões, criar anúncios de qualquer
									forma e selecionar palavras chaves no achismo é o que
									a maioria dos gestores de tráfego fazem, mas isso não
									é o suficiente. Na Aggencia trabalhamos de uma forma
									diferente.
								</span>
								<span className={clsx("inline-block", "mt-4")}>
									Buscamos entender a sua empresa, as limitações, os
									objetivos, qual solução você vende. Além de estudar
									profundamente a sua persona (público comprador).
								</span>
								<span className={clsx("inline-block", "mt-4")}>
									Essa é a parte principal para se ter anúncios
									vencedores e conseguir vender todos os dias no
									Google. Cuidamos da verba disponibilizada pelos
									nossos clientes como se fossem nosso, não gastaremos
									com cliques sujos de pessoas curiosas que não vão
									comprar o seu produto.
								</span>
							</p>
						</div>
					</div>
				</SectionReveal>
			</main>
			<footer className={clsx("mt-24", "bg-[#FF5100]", "h-28")}>
				<div
					className={clsx(
						"container",
						"m-auto",
						"flex",
						"flex-row",
						"items-center",
						"h-full",
						"justify-between",
						"gap-8"
					)}
				>
					<div
						className={clsx("flex", "flex-col", "gap-2", "items-center")}
					>
						<h2
							className={clsx(
								productSans.className,
								"font-bold",
								"text-white",
								"text-xl"
							)}
						>
							Aggencia
						</h2>
						<div
							className={clsx(
								"flex",
								"flex-row",
								"items-center",
								"gap-4"
							)}
						>
							<BsFacebook size={28} color="white" />
							<BsInstagram size={28} color="white" />
						</div>
					</div>
					<div
						className={clsx("flex", "flex-row", "items-center", "gap-8")}
					>
						<p
							className={clsx(
								productSans.className,
								"font-bold",
								"text-xl",
								"text-white",
								"hover:cursor-pointer",
								"hover:opacity-40"
							)}
						>
							Método
						</p>
						<p
							className={clsx(
								productSans.className,
								"font-bold",
								"text-xl",
								"text-white",
								"hover:cursor-pointer",
								"hover:opacity-40"
							)}
						>
							Especialidades
						</p>
						<p
							className={clsx(
								productSans.className,
								"font-bold",
								"text-xl",
								"text-white",
								"hover:cursor-pointer",
								"hover:opacity-40"
							)}
						>
							Testemunhos
						</p>
						<p
							className={clsx(
								productSans.className,
								"font-bold",
								"text-xl",
								"text-white",
								"hover:cursor-pointer",
								"hover:opacity-40"
							)}
						>
							Sobre Nós
						</p>
					</div>
				</div>
			</footer>
		</>
	);
}
